# Generated by Django 3.1.1 on 2020-09-15 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('has_veggie', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
