# Generated by Django 3.0.6 on 2020-10-19 17:08

import api_company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expired_annual_leave_last_year',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=api_company.models.name_file),
        ),
        migrations.AlterField(
            model_name='company',
            name='maximum_level_approved',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
