# Generated by Django 2.2 on 2020-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_team', '0002_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
