# Generated by Django 3.0.6 on 2020-10-19 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(null=True)),
                ('descriptions', models.TextField(null=True)),
                ('year', models.IntegerField(default=2020)),
            ],
            options={
                'db_table': 'hr_holidays',
            },
        ),
        migrations.CreateModel(
            name='Lunchdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('veggie', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hr_lunchdate',
            },
        ),
        migrations.CreateModel(
            name='TypeOff',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Insurance pay'), (0, 'Company pay')], default=0)),
                ('is_ot_days', models.BooleanField(blank=True, default=False)),
                ('is_paid_salary', models.BooleanField(blank=True, default=True)),
                ('descriptions', models.TextField()),
                ('add_sub_day_off', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hr_type_off',
            },
        ),
        migrations.CreateModel(
            name='RequestOff',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_user.Profile')),
                ('type_off', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_workday.TypeOff')),
            ],
            options={
                'db_table': 'hr_request_off',
            },
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_id', to='api_user.Profile')),
                ('request_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_detail', to='api_workday.RequestOff')),
            ],
            options={
                'db_table': 'hr_request_detail',
            },
        ),
        migrations.CreateModel(
            name='RemainLeave',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(default=2020)),
                ('bonus', models.FloatField(default=0)),
                ('annual_leave', models.FloatField(default=0)),
                ('current_days_off', models.FloatField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_user.Profile')),
            ],
            options={
                'db_table': 'hr_remain_year',
            },
        ),
        migrations.CreateModel(
            name='ProposeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('lunch', models.CharField(default='No', max_length=255)),
                ('start_hour', models.CharField(max_length=255, null=True)),
                ('end_hour', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='api_user.Profile')),
            ],
            options={
                'db_table': 'hr_propose_leave',
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_date', to='api_workday.Lunchdate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_profile', to='api_user.Profile')),
            ],
            options={
                'db_table': 'hr_lunch',
            },
        ),
        migrations.CreateModel(
            name='DateOff',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(null=True)),
                ('type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('All day', 'All day')], default='All day', max_length=255, null=True)),
                ('lunch', models.BooleanField(default=False)),
                ('request_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_off', to='api_workday.RequestOff')),
            ],
            options={
                'db_table': 'hr_date_off',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(default=None, max_length=255, null=True)),
                ('reason', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('All day', 'All day')], default='All day', max_length=255, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date', to='api_user.Profile')),
            ],
            options={
                'db_table': 'hr_date',
            },
        ),
    ]
