# Generated by Django 3.0.6 on 2020-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_workday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='year',
        ),
        migrations.AddField(
            model_name='remainleave',
            name='annual_leave_last_year',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='typeoff',
            name='is_ot_days',
            field=models.IntegerField(choices=[(0, 'In Week'), (1, 'End Week'), (2, 'All Week')], default=0),
        ),
    ]
