# Generated by Django 2.2 on 2020-10-14 14:17

from django.db import migrations, models
from api_user.constants.titles import Titles


def load_titles(apps, schema_editor):
    title_model = apps.get_model("api_user", "Titles")
    for title in Titles.TITLES:
        title_model.objects.create(title=title[0])


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hr_titles',
            },
        ),
        migrations.RunPython(load_titles),
    ]
