# Generated by Django 2.2 on 2020-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(0, 'male'), (1, 'female'), (2, 'other')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
