# Generated by Django 2.2.7 on 2020-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_auto_20201020_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maximum_level_approved',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
