
name: Test Matrix
on: push
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [job-one, job-two]
    env:
      LOCAL_LIBRARY_STATUS: false
      LOCAL_AUTOMATION_STATUS: false
      LOCAL_HOCPC_STATUS: false
    steps:
      - uses: actions/checkout@v2
      - name: Run test with ${{matrix.os}}
        run: |
          echo "hello"
          if [ "${{ matrix.os}}" == "job-one" ]; then
              echo "This is job one"
              echo "LOCAL_AUTOMATION_STATUS=true" >> $GITHUB_ENV
          elif [ "${{ matrix.os}}" == "job-two" ]; then
              echo "this is job two"
              echo "LOCAL_LIBRARY_STATUS=true" >> $GITHUB_ENV
          else
              echo "he"
          fi

  check-build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result == 'success' }}
        run: |
          echo "WF_ENV: ${{env.LOCAL_LIBRARY_STATUS}}"
          echo "JOB_ENV: ${{env.LOCAL_AUTOMATION_STATUS}}"

