
name: Test Matrix
on: push
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [job-one, job-two]
    steps:
      - uses: actions/checkout@v2
      - name: Run test with ${{matrix.os}}
        run: |
          echo "hello"
          if [ "${{ matrix.os}}" == "job-one" ]; then
              echo "This is job one"
          elif [ "${{ matrix.os}}" == "job-two" ]
              echo "this is job two"
          else
              echo "he"
          fi

  check-build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: build false
