
name: Test Matrix
on: push
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [job-one, job-two]
    env:
      LOCAL_LIBRARY_STATUS: false
      LOCAL_AUTOMATION_STATUS: false
      LOCAL_HOCPC_STATUS: false
    steps:
      - uses: actions/checkout@v2
      - name: Run test with ${{matrix.os}}
        run: |
          echo "hello"
          if [ "${{ matrix.os}}" == "job-one" ]; then
              echo "action_state=yellow" >> $GITHUB_ENV
              echo "This is job one"
              echo "action_state=red" >> $GITHUB_ENV

          elif [ "${{ matrix.os}}" == "job-two" ]; then
              echo "action_statee=black" >> $GITHUB_ENV
              echo "this is job two"
             echo "action_statee=blue" >> $GITHUB_ENV
          else
              echo "he"
          fi

  check-build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result == 'success' }}
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.action_statee }}"

