
name: Test Matrix
on: push
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [job-one, job-two]
    steps:
      - uses: actions/checkout@v2
      - if: ${{matrix.os}} == job-one
        name: Run test with ${{matrix.os}}
        run: |
          echo "this is one"
          echo "continue"
      - if: ${{matrix.os}} == job-two
        name: Run test with ${{matrix.os}}
        run: |
          echo "this is two"
          echo "continue"

  check-build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: build false
