name: Matrixsc
#2saa
on: push
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        ubuntu: [ "ubuntu:18.04", "ubuntu:16.04", "ubuntu:20.04"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.6
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test ${{ matrix.ubuntu }}
        uses: actions/ubuntu-version@v1
        with:
          ubuntu-version: ${{matrix.ubuntu}}
        run: |
          cd src/
          python3 manage.py test
        continue-on-error: true


