

name: Sample Should Fail All Runs
on: push
jobs:
  job:
    runs-on: self-hosted
    strategy:
      matrix:
        run: ['run1', 'run2', 'run3']
#      fail-fast: true
      max-parallel: 2
    steps:
      - uses: actions/checkout@v2
        with:
          run: ${{matrix.run}}
      - name: Run test with ${{matrix.run}}
        run: |
          echo "continue"
          cd src
          python3 manage.py test
