

name: Sample Should Fail All Runs
on: push
jobs:
  job:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [self-hosted.lable]
    steps:
      - uses: actions/checkout@v2
      - name: Run test with ${{matrix.os}}
        run: |
          cd src
          python3 manage.py test
