name: Matrixsc
#2saa
on: push
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        container: [ "ubuntu:18.04", "fedora:31", "opensuse/leap:42.3", "centos8" ]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.6
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test ${{ matrix.container }}
        with:
          docker-version: ${{matrix.container}}
        run: |
          cd src/
          python3 manage.py test


