

name: Sample Should Fail All Runs
on: push
jobs:
  job:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [job-one, job-two]
    steps:
      - uses: actions/checkout@v2
      - name: Run test with ${{github.self_hosted_labels}}
        run: |
          echo "continue"
          cd src
          python3 manage.py test
#
